@extends('layouts.app')


@section('content')

<section class="m-t-3 container m-b-2">

    <div>
        <h2> Privacy Policy </h2>
        <p>
            Last updated: March 07, 2022 

 

            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. 
            
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Template. 
        </p>
    </div>

    <div>
        <h2>Interpretation and Definitions </h2>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. </p>
    </div>

    <div>
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy: </p>
        <ul>

            <li>Account means a unique account created for You to access our Service or parts of our Service. </li>
            <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Cornwall Cottages, Cornwall, England. </li>
            <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. </li>
            <li>Country refers to: United Kingdom </li>
            <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. </li>
            <li>Personal Data is any information that relates to an identified or identifiable individual. </li>
            <li>Service refers to the Website. </li>
            <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. </li>
            <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). </li>
            <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. </li>
   

        </ul>
    </div>
    <div>
        <h3>Collecting and Using Your Personal Data </h3>
        <h4>Personal Data </h4>
        <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: 
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data </li>
            </ul>

        </p>
    </div>





   

</section>
@endsection
